//! Loading the embedded standard library, and the schemes of built-in names.
//!
//! The standard library is a set of `.fai` modules embedded at build time (see
//! `build.rs`). [`load_std`] registers each as a synthetic, high-durability
//! input under the `<std>/` path namespace; [`is_std_path`] recognizes them so
//! the driver can keep them out of user-facing surfaces and resolution can grant
//! them access to the prelude-private `Prim` intrinsics.
//!
//! [`builtin_scheme`] gives the types of the names that are *not* ordinary `.fai`
//! definitions: the boolean literals, the `Console` capability placeholder, and
//! the Rust-implemented intrinsics reached through `Prim`.
//!
//! The `<std>/` path convention itself ([`fai_db::is_std_path`]) lives in
//! `fai-db`, shared with the lower phases that classify files by path.

use fai_db::{Durability, FaiDatabase, STD_PATH_PREFIX};
use fai_span::SourceId;
use fai_syntax::Symbol;

use crate::ty::{Con, Scheme, Ty};

// The embedded `(file name, source text)` table, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/std_sources.rs"));

/// Loads every embedded standard-library module into `db` as a high-durability
/// synthetic input, returning their [`SourceId`]s in `STD_SOURCES` order.
pub fn load_std(db: &mut FaiDatabase) -> Vec<SourceId> {
    STD_SOURCES
        .iter()
        .map(|(name, source)| {
            db.add_source_with_durability(
                format!("{STD_PATH_PREFIX}{name}").into(),
                (*source).to_owned(),
                Durability::HIGH,
            )
        })
        .collect()
}

/// The scheme of a built-in name, if known.
///
/// Covers the boolean literals, the `Console` capability member, and the
/// Rust-implemented intrinsics (reached as `Prim.*`). Everything else the
/// standard library offers is an ordinary `.fai` definition typed through normal
/// inference.
#[must_use]
pub fn builtin_scheme(name: Symbol) -> Option<Scheme> {
    Some(match name.as_str() {
        "true" | "false" => Scheme::mono(Ty::bool()),
        // The Console capability's sole member, reached as `Console.writeLine`
        // (a qualified builtin). A placeholder until interfaces/records land:
        // `Runtime -> String -> Unit`.
        "writeLine" => {
            Scheme::mono(Ty::arrows([Ty::Con(Con::Runtime), Ty::Con(Con::String)], Ty::Unit))
        }
        "intToString" => Scheme::mono(Ty::arrow(Ty::int(), Ty::Con(Con::String))),
        "floatToString" => Scheme::mono(Ty::arrow(Ty::Con(Con::Float), Ty::Con(Con::String))),
        "intToFloat" => Scheme::mono(Ty::arrow(Ty::int(), Ty::Con(Con::Float))),
        "floatToInt" => Scheme::mono(Ty::arrow(Ty::Con(Con::Float), Ty::int())),
        "sqrt" => Scheme::mono(Ty::arrow(Ty::Con(Con::Float), Ty::Con(Con::Float))),
        "not" => Scheme::mono(Ty::arrow(Ty::bool(), Ty::bool())),
        // String operations.
        "stringLength" => Scheme::mono(Ty::arrow(Ty::Con(Con::String), Ty::int())),
        "toUpper" | "toLower" | "trim" => {
            Scheme::mono(Ty::arrow(Ty::Con(Con::String), Ty::Con(Con::String)))
        }
        "stringContains" => {
            Scheme::mono(Ty::arrows([Ty::Con(Con::String), Ty::Con(Con::String)], Ty::bool()))
        }
        "stringConcat" => Scheme::mono(Ty::arrows(
            [Ty::Con(Con::String), Ty::Con(Con::String)],
            Ty::Con(Con::String),
        )),
        "split" => Scheme::mono(Ty::arrows(
            [Ty::Con(Con::String), Ty::Con(Con::String)],
            Ty::list(Ty::Con(Con::String)),
        )),
        "join" => Scheme::mono(Ty::arrows(
            [Ty::Con(Con::String), Ty::list(Ty::Con(Con::String))],
            Ty::Con(Con::String),
        )),
        _ => return None,
    })
}
