//! Loading the embedded standard library, and the schemes of built-in names.
//!
//! The standard library is a set of `.fai` modules embedded at build time (see
//! `build.rs`). [`load_std`] registers each as a synthetic, high-durability
//! input under the `<std>/` path namespace; [`is_std_path`] recognizes them so
//! the driver can keep them out of user-facing surfaces and resolution can grant
//! them access to the prelude-private `Prim` intrinsics.
//!
//! [`builtin_scheme`] gives the types of the names that are *not* ordinary `.fai`
//! definitions: the boolean literals, the `Console` capability placeholder, and
//! the Rust-implemented intrinsics reached through `Prim`.
//!
//! The `<std>/` path convention itself ([`fai_db::is_std_path`]) lives in
//! `fai-db`, shared with the lower phases that classify files by path.

use fai_db::{Durability, FaiDatabase, STD_PATH_PREFIX};
use fai_span::SourceId;
use fai_syntax::Symbol;

use crate::ty::{Con, Scheme, Ty, TyVarId};

// The embedded `(file name, source text)` table, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/std_sources.rs"));

/// Loads every embedded standard-library module into `db` as a high-durability
/// synthetic input, returning their [`SourceId`]s in `STD_SOURCES` order.
pub fn load_std(db: &mut FaiDatabase) -> Vec<SourceId> {
    STD_SOURCES
        .iter()
        .map(|(name, source)| {
            db.add_source_with_durability(
                format!("{STD_PATH_PREFIX}{name}").into(),
                (*source).to_owned(),
                Durability::HIGH,
            )
        })
        .collect()
}

/// The host return shape `(Bool * String)` that the standard library unwraps
/// into a `Result`/`Option`: a success/found flag and a payload (contents, value,
/// or error message).
fn ok_string_pair() -> Ty {
    Ty::Tuple(vec![Ty::bool(), Ty::Con(Con::String)])
}

/// The scheme of a built-in name, if known.
///
/// Covers the boolean literals, the `Console` capability member, and the
/// Rust-implemented intrinsics (reached as `Prim.*`). Everything else the
/// standard library offers is an ordinary `.fai` definition typed through normal
/// inference.
#[must_use]
pub fn builtin_scheme(name: Symbol) -> Option<Scheme> {
    Some(match name.as_str() {
        "true" | "false" => Scheme::mono(Ty::bool()),
        // Capability hosts (prelude-private `Prim.*`), reached only through the
        // `Runtime` value the standard library builds and `main` receives.
        "consoleWriteLine" => Scheme::mono(Ty::arrow(Ty::Con(Con::String), Ty::Unit)),
        "clockNow" => Scheme::mono(Ty::arrow(Ty::Unit, Ty::int())),
        "randomNextInt" => Scheme::mono(Ty::arrow(Ty::int(), Ty::int())),
        // FileSystem/Env hosts return primitives the standard library wraps into
        // `Result`/`Option`: a `(Bool * String)` is `(ok?/found?, payload)`.
        "fileRead" => Scheme::mono(Ty::arrow(Ty::Con(Con::String), ok_string_pair())),
        "fileWrite" => {
            Scheme::mono(Ty::arrows([Ty::Con(Con::String), Ty::Con(Con::String)], ok_string_pair()))
        }
        "envGet" => Scheme::mono(Ty::arrow(Ty::Con(Con::String), ok_string_pair())),
        "envArgs" => Scheme::mono(Ty::arrow(Ty::Unit, Ty::list(Ty::Con(Con::String)))),
        // Bitwise integer intrinsics.
        "intAnd"
        | "intOr"
        | "intXor"
        | "intShiftLeft"
        | "intShiftRight"
        | "intShiftRightLogical" => Scheme::mono(Ty::arrows([Ty::int(), Ty::int()], Ty::int())),
        "intComplement" => Scheme::mono(Ty::arrow(Ty::int(), Ty::int())),
        "intToString" => Scheme::mono(Ty::arrow(Ty::int(), Ty::Con(Con::String))),
        "floatToString" => Scheme::mono(Ty::arrow(Ty::Con(Con::Float), Ty::Con(Con::String))),
        "intToFloat" => Scheme::mono(Ty::arrow(Ty::int(), Ty::Con(Con::Float))),
        "floatToInt" => Scheme::mono(Ty::arrow(Ty::Con(Con::Float), Ty::int())),
        "sqrt" => Scheme::mono(Ty::arrow(Ty::Con(Con::Float), Ty::Con(Con::Float))),
        "floatFromBits" => Scheme::mono(Ty::arrow(Ty::int(), Ty::Con(Con::Float))),
        "floatToBits" => Scheme::mono(Ty::arrow(Ty::Con(Con::Float), Ty::int())),
        // Char conversions. A Char shares the immediate encoding with Int, so the
        // code-point conversions are typed bitcasts; `isValidCharCode` guards the
        // partial `Int -> Char` direction so `Char.fromCode` can return `Option`.
        "charToString" => Scheme::mono(Ty::arrow(Ty::Con(Con::Char), Ty::Con(Con::String))),
        "charToCode" => Scheme::mono(Ty::arrow(Ty::Con(Con::Char), Ty::int())),
        "charFromCode" => Scheme::mono(Ty::arrow(Ty::int(), Ty::Con(Con::Char))),
        "isValidCharCode" => Scheme::mono(Ty::arrow(Ty::int(), Ty::bool())),
        "not" => Scheme::mono(Ty::arrow(Ty::bool(), Ty::bool())),
        // String operations.
        "stringLength" => Scheme::mono(Ty::arrow(Ty::Con(Con::String), Ty::int())),
        "toUpper" | "toLower" | "trim" => {
            Scheme::mono(Ty::arrow(Ty::Con(Con::String), Ty::Con(Con::String)))
        }
        "stringContains" => {
            Scheme::mono(Ty::arrows([Ty::Con(Con::String), Ty::Con(Con::String)], Ty::bool()))
        }
        "stringConcat" => Scheme::mono(Ty::arrows(
            [Ty::Con(Con::String), Ty::Con(Con::String)],
            Ty::Con(Con::String),
        )),
        "split" => Scheme::mono(Ty::arrows(
            [Ty::Con(Con::String), Ty::Con(Con::String)],
            Ty::list(Ty::Con(Con::String)),
        )),
        "join" => Scheme::mono(Ty::arrows(
            [Ty::Con(Con::String), Ty::list(Ty::Con(Con::String))],
            Ty::Con(Con::String),
        )),
        // Array primitives — the only *polymorphic* intrinsics, quantified over the
        // element type `'a` (instantiated fresh at each use). The standard
        // library's `Array` module wraps these (reordering to collection-last and
        // adding bounds checks); the runtime takes the array operand first, so the
        // intrinsic types match the `fai_array_*` calling convention.
        "arrayWithCapacity" => array_scheme(|a| Ty::arrow(Ty::int(), Ty::array(a))),
        "arrayLength" => array_scheme(|a| Ty::arrow(Ty::array(a), Ty::int())),
        "arrayGet" => array_scheme(|a| Ty::arrows([Ty::array(a.clone()), Ty::int()], a)),
        "arraySet" => {
            array_scheme(|a| Ty::arrows([Ty::array(a.clone()), Ty::int(), a.clone()], Ty::array(a)))
        }
        "arrayPush" => {
            array_scheme(|a| Ty::arrows([Ty::array(a.clone()), a.clone()], Ty::array(a)))
        }
        _ => return None,
    })
}

/// Builds a scheme quantified over a single element type variable `'a`, given a
/// function from that variable to the intrinsic's type. The element type is the
/// canonical first quantified variable, freshened at each instantiation.
fn array_scheme(build: impl FnOnce(Ty) -> Ty) -> Scheme {
    let var = TyVarId(0);
    Scheme::new(vec![var], build(Ty::Var(var)))
}
