//! Loading the embedded standard library, and the schemes of built-in names.
//!
//! The standard library is a set of `.fai` modules embedded at build time (see
//! `build.rs`). [`load_std`] registers each as a synthetic, high-durability
//! input under the `<std>/` path namespace; [`is_std_path`] recognizes them so
//! the driver can keep them out of user-facing surfaces and resolution can grant
//! them access to the prelude-private `Prim` intrinsics.
//!
//! [`builtin_scheme`] gives the types of the names that are *not* ordinary `.fai`
//! definitions: the boolean literals, the `Console` capability placeholder, and
//! the Rust-implemented intrinsics reached through `Prim`.
//!
//! The `<std>/` path convention itself ([`fai_db::is_std_path`]) lives in
//! `fai-db`, shared with the lower phases that classify files by path.

use fai_db::{Durability, FaiDatabase, STD_PATH_PREFIX};
use fai_span::SourceId;
use fai_syntax::Symbol;

use crate::ty::{Con, Scheme, Ty, TyVarId};

// The embedded `(file name, source text)` table, generated by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/std_sources.rs"));

/// Loads every embedded standard-library module into `db` as a high-durability
/// synthetic input, returning their [`SourceId`]s in `STD_SOURCES` order.
pub fn load_std(db: &mut FaiDatabase) -> Vec<SourceId> {
    STD_SOURCES
        .iter()
        .map(|(name, source)| {
            db.add_source_with_durability(
                format!("{STD_PATH_PREFIX}{name}").into(),
                (*source).to_owned(),
                Durability::HIGH,
            )
        })
        .collect()
}

/// The scheme of a built-in name, if known.
///
/// Covers the boolean literals, the `Console` capability member, and the
/// Rust-implemented intrinsics (reached as `Prim.*`). Everything else the
/// standard library offers is an ordinary `.fai` definition typed through normal
/// inference.
#[must_use]
pub fn builtin_scheme(name: Symbol) -> Option<Scheme> {
    Some(match name.as_str() {
        "true" | "false" => Scheme::mono(Ty::bool()),
        // Bitwise integer intrinsics.
        "intAnd"
        | "intOr"
        | "intXor"
        | "intShiftLeft"
        | "intShiftRight"
        | "intShiftRightLogical" => Scheme::mono(Ty::arrows([Ty::int(), Ty::int()], Ty::int())),
        "intComplement" => Scheme::mono(Ty::arrow(Ty::int(), Ty::int())),
        "intToString" => Scheme::mono(Ty::arrow(Ty::int(), Ty::Con(Con::String))),
        "floatToString" => Scheme::mono(Ty::arrow(Ty::Con(Con::Float), Ty::Con(Con::String))),
        "intToFloat" => Scheme::mono(Ty::arrow(Ty::int(), Ty::Con(Con::Float))),
        "floatToInt" => Scheme::mono(Ty::arrow(Ty::Con(Con::Float), Ty::int())),
        "sqrt" => Scheme::mono(Ty::arrow(Ty::Con(Con::Float), Ty::Con(Con::Float))),
        "floatFromBits" => Scheme::mono(Ty::arrow(Ty::int(), Ty::Con(Con::Float))),
        "floatToBits" => Scheme::mono(Ty::arrow(Ty::Con(Con::Float), Ty::int())),
        // Char conversions. A Char shares the immediate encoding with Int, so the
        // code-point conversions are typed bitcasts; `isValidCharCode` guards the
        // partial `Int -> Char` direction so `Char.fromCode` can return `Option`.
        "charToString" => Scheme::mono(Ty::arrow(Ty::Con(Con::Char), Ty::Con(Con::String))),
        "charToCode" => Scheme::mono(Ty::arrow(Ty::Con(Con::Char), Ty::int())),
        "charFromCode" => Scheme::mono(Ty::arrow(Ty::int(), Ty::Con(Con::Char))),
        "isValidCharCode" => Scheme::mono(Ty::arrow(Ty::int(), Ty::bool())),
        "not" => Scheme::mono(Ty::arrow(Ty::bool(), Ty::bool())),
        // Structural three-way comparison, polymorphic over any (comparable) type
        // — `Prelude.compare` wraps it. Like the other structural operators it
        // carries no surface constraint; a non-comparable instantiation (a
        // function type) is a runtime guard, not a type error.
        "compare" => single_var_scheme(|a| Ty::arrows([a.clone(), a], Ty::int())),
        // Structural hash, polymorphic over any (hashable) type — the `HashDict`/
        // `HashSet` containers wrap it. Like `compare` it carries no surface
        // constraint; a function-typed instantiation is a runtime guard.
        "hash" => single_var_scheme(|a| Ty::arrow(a, Ty::int())),
        // String operations.
        "stringLength" => Scheme::mono(Ty::arrow(Ty::Con(Con::String), Ty::int())),
        "toUpper" | "toLower" | "trim" => {
            Scheme::mono(Ty::arrow(Ty::Con(Con::String), Ty::Con(Con::String)))
        }
        "stringContains" => {
            Scheme::mono(Ty::arrows([Ty::Con(Con::String), Ty::Con(Con::String)], Ty::bool()))
        }
        "stringConcat" => Scheme::mono(Ty::arrows(
            [Ty::Con(Con::String), Ty::Con(Con::String)],
            Ty::Con(Con::String),
        )),
        "split" => Scheme::mono(Ty::arrows(
            [Ty::Con(Con::String), Ty::Con(Con::String)],
            Ty::list(Ty::Con(Con::String)),
        )),
        "join" => Scheme::mono(Ty::arrows(
            [Ty::Con(Con::String), Ty::list(Ty::Con(Con::String))],
            Ty::Con(Con::String),
        )),
        // The contiguous twins of `split`/`join` (monomorphic over `Array String`):
        // they build / consume an `Array` rather than a `List`.
        "arraySplit" => Scheme::mono(Ty::arrows(
            [Ty::Con(Con::String), Ty::Con(Con::String)],
            Ty::array(Ty::Con(Con::String)),
        )),
        "arrayJoin" => Scheme::mono(Ty::arrows(
            [Ty::Con(Con::String), Ty::array(Ty::Con(Con::String))],
            Ty::Con(Con::String),
        )),
        // Substring views: char-indexed start/length, source string last (matching
        // the `fai_string_*` calling convention).
        "substring" => Scheme::mono(Ty::arrows(
            [Ty::int(), Ty::int(), Ty::Con(Con::String)],
            Ty::Con(Con::String),
        )),
        "take" | "drop" => {
            Scheme::mono(Ty::arrows([Ty::int(), Ty::Con(Con::String)], Ty::Con(Con::String)))
        }
        // Array primitives — the only *polymorphic* intrinsics, quantified over the
        // element type `'a` (instantiated fresh at each use). The standard
        // library's `Array` module wraps these (reordering to collection-last and
        // adding bounds checks); the runtime takes the array operand first, so the
        // intrinsic types match the `fai_array_*` calling convention.
        "arrayWithCapacity" => single_var_scheme(|a| Ty::arrow(Ty::int(), Ty::array(a))),
        "arrayLength" => single_var_scheme(|a| Ty::arrow(Ty::array(a), Ty::int())),
        "arrayGet" => single_var_scheme(|a| Ty::arrows([Ty::array(a.clone()), Ty::int()], a)),
        "arraySet" => single_var_scheme(|a| {
            Ty::arrows([Ty::array(a.clone()), Ty::int(), a.clone()], Ty::array(a))
        }),
        "arrayPush" => {
            single_var_scheme(|a| Ty::arrows([Ty::array(a.clone()), a.clone()], Ty::array(a)))
        }
        // Binary byte-buffer primitives (the standard library's `Bytes` module
        // wraps these). Bytes are read/written as `Int` 0–255; slice takes
        // start/end byte indices with the buffer last.
        "bytesLength" => Scheme::mono(Ty::arrow(Ty::Con(Con::Bytes), Ty::int())),
        "bytesGet" => Scheme::mono(Ty::arrows([Ty::Con(Con::Bytes), Ty::int()], Ty::int())),
        "bytesConcat" => Scheme::mono(Ty::arrows(
            [Ty::Con(Con::Bytes), Ty::Con(Con::Bytes)],
            Ty::Con(Con::Bytes),
        )),
        "bytesSlice" => Scheme::mono(Ty::arrows(
            [Ty::int(), Ty::int(), Ty::Con(Con::Bytes)],
            Ty::Con(Con::Bytes),
        )),
        "bytesFromList" => Scheme::mono(Ty::arrow(Ty::list(Ty::int()), Ty::Con(Con::Bytes))),
        "bytesToList" => Scheme::mono(Ty::arrow(Ty::Con(Con::Bytes), Ty::list(Ty::int()))),
        "bytesFromString" => Scheme::mono(Ty::arrow(Ty::Con(Con::String), Ty::Con(Con::Bytes))),
        "bytesToString" => Scheme::mono(Ty::arrow(Ty::Con(Con::Bytes), Ty::Con(Con::String))),
        "bytesIsUtf8" => Scheme::mono(Ty::arrow(Ty::Con(Con::Bytes), Ty::bool())),
        _ => return None,
    })
}

/// Builds a scheme quantified over a single type variable `'a` (an array element,
/// or the operand of `compare`), given a function from that variable to the
/// intrinsic's type. The variable is the canonical first quantified variable,
/// freshened at each instantiation.
fn single_var_scheme(build: impl FnOnce(Ty) -> Ty) -> Scheme {
    let var = TyVarId(0);
    Scheme::new(vec![var], build(Ty::Var(var)))
}
